# Generated by Django 4.2 on 2024-08-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskforge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskavailablemodel',
            name='c_date',
        ),
        migrations.AddField(
            model_name='taskavailablemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
